### ISSUE TITLE
layer skip eval.py gives same result even if I change the exit layer number

### ISSUE THREAD

**Issue by abubakar12** [facebookresearch/LayerSkip#15]
```
torchrun eval.py --model facebook/layerskip-llama3.2-1B \
--tasks boolq \
--generation_strategy self_speculative \
--exit_layer 2 \
--num_speculations 6 
```

No matter what parameter I change in the exit _layer , accuracy remains same for the model. i changed exit_layer from 2 to 20, nothing changed in accuracy. result is same for all the tasks involving one word answer or any thing  that goes loglikelihood instead of generate_until thing.

**Comment by mostafaelhoushi** [comment]
Hi @abubakar12 
Thanks for trying LayerSkip.

Note that you are using `--generation_strategy self_speculative`, which means that the model generates tokens by exiting early, and then verifying/fixing tokens by using the remaining layers. So accuracy should not change by changing exit layer should not affect accuracy (especially if you use `--sample False`).
Regarding speed, we can only obtain speedups from generation tasks (e.g., gsm8k or cnn_dailymail), while classificaton tasks, i.e., multiple choice question tasks (e.g., piqa, social_iqa) or True/False question tasks (e.g., boolq) will not lead to speedup.

However, if you use `--generation_strategy autoregressive`, the model will exit early without fixing itself, then you will definitely see different accuracies when exiting at different layers.

**Comment by abubakar12** [comment]
thank you @mostafaelhoushi . this worked.
