### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by mostafaelhoushi** [facebookresearch/LayerSkip#7]

**Comment by HimanshuJanbandhu** [comment]
Yes definitely.
- I'm assuming we'll use `pytest` library for testing
- use [pytest-mock](https://github.com/pytest-dev/pytest-mock) for mocking
- I'll create a file in test directory, corresponding to each file in https://github.com/facebookresearch/LayerSkip/tree/main/self_speculation

**Comment by mostafaelhoushi** [comment]
Sounds good! Thanks again @HimanshuJanbandhu !

**Comment by mostafaelhoushi** [comment]
Hi @HimanshuJanbandhu . Please note that there were mistakes in correctness.py and I just fixed them (in this commit ce4a3bef71e3c4f87f06cee5f817fb851f1820a3 ). So please pull latest from main to ensure you are working on a fixed version of the code.

**Comment by HimanshuJanbandhu** [comment]
Okay, I'll use the latest pull

**Comment by HimanshuJanbandhu** [comment]
Hey raised a pull request. I encountered some issues with self_speculation_generator.py, maybe with your suggestions I can improve the tests suite.
Let me know if you have any adivse regarding this.
https://github.com/facebookresearch/LayerSkip/pull/14
